# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a20a8542d8264ad3578d9b78d9bb6a39a08007892dd55bb8047812c27183e1f50e4f28e098d31c5c6dafff79d3e41c6a214c9656c374e7720b36d3b6f0d33f16

test:
  secret_key_base: 22b476da363714e97b176f0d151fae2abba02a81acc06daf22e079f6ca9b9290b96fb0dc9275dfc9a0854694094bd6477c2497c728f9aac61229fe03edcdb9cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
